2014/10/17 04:50:15 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'journal_analysis.test' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `test`.
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 04:50:16 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'journal_analysis.test' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `test`.
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 04:50:20 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'journal_analysis.int' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `int`.
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 04:50:24 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'journal_analysis.test' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `Test`.
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 04:51:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "profile".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('profile')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/profile
HTTP_REFERER=http://drivesoftcenter.net/tutorial/yii/%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B8%87%E0%B8%B2%E0%B8%99-Gii-%E0%B8%82%E0%B8%AD%E0%B8%87-Yii-Framework
---
2014/10/17 04:51:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "profile".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('profile')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/profile
HTTP_REFERER=http://drivesoftcenter.net/tutorial/yii/%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B8%87%E0%B8%B2%E0%B8%99-Gii-%E0%B8%82%E0%B8%AD%E0%B8%87-Yii-Framework
---
2014/10/17 04:51:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "profile".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('profile')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/profile
HTTP_REFERER=http://drivesoftcenter.net/tutorial/yii/%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B8%87%E0%B8%B2%E0%B8%99-Gii-%E0%B8%82%E0%B8%AD%E0%B8%87-Yii-Framework
---
2014/10/17 05:00:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/user
---
2014/10/17 05:00:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/index
---
2014/10/17 05:00:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "yii".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('yii')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/yii
---
2014/10/17 05:05:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "profile".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('profile')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/profile
HTTP_REFERER=http://drivesoftcenter.net/tutorial/yii/%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B8%87%E0%B8%B2%E0%B8%99-Gii-%E0%B8%82%E0%B8%AD%E0%B8%87-Yii-Framework
---
2014/10/17 05:06:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "JournalImpactFactor.php".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('JournalImpactFa...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/JournalImpactFactor.php
---
2014/10/17 15:01:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/user
---
2014/10/17 15:05:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "profile".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('profile')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/profile
HTTP_REFERER=http://drivesoftcenter.net/tutorial/yii/%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B8%87%E0%B8%B2%E0%B8%99-Gii-%E0%B8%82%E0%B8%AD%E0%B8%87-Yii-Framework
---
2014/10/17 15:10:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "userLogin".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('userLogin')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/userLogin
HTTP_REFERER=http://drivesoftcenter.net/tutorial/yii/%E0%B8%AA%E0%B8%A3%E0%B9%89%E0%B8%B2%E0%B8%87%E0%B8%AB%E0%B8%99%E0%B9%89%E0%B8%B2%E0%B8%AA%E0%B8%A1%E0%B8%B1%E0%B8%84%E0%B8%A3%E0%B8%AA%E0%B8%A1%E0%B8%B2%E0%B8%8A%E0%B8%B4%E0%B8%81
---
2014/10/17 16:01:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "JournalImpactFactorController".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('JournalImpactFa...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/JournalImpactFactorController
---
2014/10/17 16:01:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "JournalImpactFactorController".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('JournalImpactFa...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/JournalImpactFactorController
---
2014/10/17 16:02:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "JournalScimagoController".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('JournalScimagoC...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/JournalScimagoController
---
2014/10/17 16:02:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "JournalScimagoController/view".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('JournalScimagoC...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/JournalScimagoController/view
---
2014/10/17 16:02:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "view/JournalScimagoController/view".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('view/JournalSci...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/view/JournalScimagoController/view
---
2014/10/17 16:02:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "view/JournalScimagoController".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('view/JournalSci...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/view/JournalScimagoController
---
2014/10/17 16:02:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "views/JournalScimagoController".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('views/JournalSc...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/views/JournalScimagoController
---
2014/10/17 16:03:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "view/JournalScimagoController".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('view/JournalSci...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/view/JournalScimagoController
---
2014/10/17 16:03:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "view/JournalScimagoController/view".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('view/JournalSci...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/view/JournalScimagoController/view
---
2014/10/17 16:03:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "JournalScimagoController/view".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('JournalScimagoC...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/JournalScimagoController/view
---
2014/10/17 16:03:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "JournalScimagoController".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('JournalScimagoC...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/JournalScimagoController
---
2014/10/17 16:03:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "JournalImpactFactorController".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('JournalImpactFa...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/JournalImpactFactorController
---
2014/10/17 16:03:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "JournalScimagoController".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('JournalScimagoC...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/JournalScimagoController
---
2014/10/17 16:04:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "JournalScimagoController".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('JournalScimagoC...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/JournalScimagoController
---
2014/10/17 17:01:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "index" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('HelloWorld')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/HelloWorld
---
2014/10/17 17:01:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "HelloWorld.php".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('HelloWorld.php')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/HelloWorld.php
---
2014/10/17 17:10:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "view.php" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('view.php')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view.php')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('journalScimago/...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/journalScimago/view.php
---
2014/10/17 17:10:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "_view.php" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('_view.php')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('_view.php')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('journalScimago/...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/journalScimago/_view.php
---
2014/10/17 17:10:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "_view" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('_view')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('_view')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('journalScimago/...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/journalScimago/_view
---
2014/10/17 18:49:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "index.php" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('index.php')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index.php')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('post/index.php')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/post/index.php
---
2014/10/17 20:04:26 [error] [php] json_encode() expects parameter 2 to be long, array given (C:\xampp\htdocs\testyii\protected\views\journalScimago\_view.php:9)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): JournalScimagoController->renderInternal()
#1 C:\xampp\htdocs\yii\framework\zii\widgets\CListView.php(291): JournalScimagoController->renderFile()
#2 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(167): CListView->renderItems()
#3 unknown(0): CListView->renderSection()
#4 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(150): preg_replace_callback()
#5 C:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(135): CListView->renderContent()
#6 C:\xampp\htdocs\yii\framework\web\CBaseController.php(173): CListView->run()
#7 C:\xampp\htdocs\testyii\protected\views\journalScimago\index.php(20): JournalScimagoController->widget()
#8 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#9 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): JournalScimagoController->renderInternal()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(869): JournalScimagoController->renderFile()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(782): JournalScimagoController->renderPartial()
#12 C:\xampp\htdocs\testyii\protected\controllers\JournalScimagoController.php(128): JournalScimagoController->render()
#13 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): JournalScimagoController->actionIndex()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): JournalScimagoController->runAction()
#16 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#18 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): JournalScimagoController->filterAccessControl()
#19 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#20 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#21 C:\xampp\htdocs\yii\framework\web\CController.php(265): JournalScimagoController->runActionWithFilters()
#22 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): JournalScimagoController->run()
#23 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#24 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#25 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/journalScimago
in C:\xampp\htdocs\testyii\protected\views\journalScimago\_view.php (9)
in C:\xampp\htdocs\testyii\protected\views\journalScimago\index.php (20)
in C:\xampp\htdocs\testyii\protected\controllers\JournalScimagoController.php (128)
2014/10/17 21:03:03 [error] [php] Invalid argument supplied for foreach() (C:\xampp\htdocs\yii\framework\web\CWidgetFactory.php:160)
Stack trace:
#0 C:\xampp\htdocs\testyii\protected\views\journalImpactFactor\index.php(20): JournalImpactFactorController->widget()
#1 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): JournalImpactFactorController->renderInternal()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(869): JournalImpactFactorController->renderFile()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(782): JournalImpactFactorController->renderPartial()
#5 C:\xampp\htdocs\testyii\protected\controllers\JournalImpactFactorController.php(128): JournalImpactFactorController->render()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): JournalImpactFactorController->actionIndex()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): JournalImpactFactorController->runAction()
#9 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#11 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): JournalImpactFactorController->filterAccessControl()
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\htdocs\yii\framework\web\CController.php(265): JournalImpactFactorController->runActionWithFilters()
#15 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): JournalImpactFactorController->run()
#16 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#17 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#18 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/journalImpactFactor
in C:\xampp\htdocs\testyii\protected\views\journalImpactFactor\index.php (20)
in C:\xampp\htdocs\testyii\protected\controllers\JournalImpactFactorController.php (128)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 21:06:54 [error] [php] include(custom_json.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWidgetFactory.php(161): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\CBaseController.php(146): CWidgetFactory->createWidget()
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(172): JournalImpactFactorController->createWidget()
#3 C:\xampp\htdocs\testyii\protected\views\journalImpactFactor\index.php(20): JournalImpactFactorController->widget()
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): JournalImpactFactorController->renderInternal()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(869): JournalImpactFactorController->renderFile()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(782): JournalImpactFactorController->renderPartial()
#8 C:\xampp\htdocs\testyii\protected\controllers\JournalImpactFactorController.php(128): JournalImpactFactorController->render()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): JournalImpactFactorController->actionIndex()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): JournalImpactFactorController->runAction()
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): JournalImpactFactorController->filterAccessControl()
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): JournalImpactFactorController->runActionWithFilters()
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): JournalImpactFactorController->run()
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/journalImpactFactor
in C:\xampp\htdocs\testyii\protected\views\journalImpactFactor\index.php (20)
in C:\xampp\htdocs\testyii\protected\controllers\JournalImpactFactorController.php (128)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 21:07:14 [error] [php] include(custom_json.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWidgetFactory.php(162): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\CBaseController.php(146): CWidgetFactory->createWidget()
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(172): JournalImpactFactorController->createWidget()
#3 C:\xampp\htdocs\testyii\protected\views\journalImpactFactor\index.php(20): JournalImpactFactorController->widget()
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): JournalImpactFactorController->renderInternal()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(869): JournalImpactFactorController->renderFile()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(782): JournalImpactFactorController->renderPartial()
#8 C:\xampp\htdocs\testyii\protected\controllers\JournalImpactFactorController.php(128): JournalImpactFactorController->render()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): JournalImpactFactorController->actionIndex()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): JournalImpactFactorController->runAction()
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): JournalImpactFactorController->filterAccessControl()
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): JournalImpactFactorController->runActionWithFilters()
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): JournalImpactFactorController->run()
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/journalImpactFactor
in C:\xampp\htdocs\testyii\protected\views\journalImpactFactor\index.php (20)
in C:\xampp\htdocs\testyii\protected\controllers\JournalImpactFactorController.php (128)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 21:07:15 [error] [php] include(custom_json.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWidgetFactory.php(162): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\CBaseController.php(146): CWidgetFactory->createWidget()
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(172): JournalImpactFactorController->createWidget()
#3 C:\xampp\htdocs\testyii\protected\views\journalImpactFactor\index.php(20): JournalImpactFactorController->widget()
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): JournalImpactFactorController->renderInternal()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(869): JournalImpactFactorController->renderFile()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(782): JournalImpactFactorController->renderPartial()
#8 C:\xampp\htdocs\testyii\protected\controllers\JournalImpactFactorController.php(128): JournalImpactFactorController->render()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): JournalImpactFactorController->actionIndex()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#11 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): JournalImpactFactorController->runAction()
#12 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#14 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): JournalImpactFactorController->filterAccessControl()
#15 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#16 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\yii\framework\web\CController.php(265): JournalImpactFactorController->runActionWithFilters()
#18 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): JournalImpactFactorController->run()
#19 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#20 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/journalImpactFactor
in C:\xampp\htdocs\testyii\protected\views\journalImpactFactor\index.php (20)
in C:\xampp\htdocs\testyii\protected\controllers\JournalImpactFactorController.php (128)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 22:37:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "journalScimago".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('journalScimago')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/journalScimago
---
2014/10/17 22:51:50 [error] [php] include(Customer.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\testyii\protected\controllers\APIController.php(46): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): ApiController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): ApiController->runActionWithFilters()
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ApiController->run()
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/api/Customer/list
in C:\xampp\htdocs\testyii\protected\controllers\APIController.php (46)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 22:52:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "Customer" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('Customer')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('Customer')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('api/Customer')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/index.php/api/Customer
---
2014/10/17 22:52:34 [error] [php] include(Customer.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\testyii\protected\controllers\APIController.php(46): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): ApiController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): ApiController->runActionWithFilters()
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ApiController->run()
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/api/Customer/list
in C:\xampp\htdocs\testyii\protected\controllers\APIController.php (46)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 22:54:21 [error] [php] include(Customer.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\testyii\protected\controllers\APIController.php(46): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): ApiController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): ApiController->runActionWithFilters()
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ApiController->run()
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/api/Customer/list
in C:\xampp\htdocs\testyii\protected\controllers\APIController.php (46)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 22:54:22 [error] [php] include(Customer.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\testyii\protected\controllers\APIController.php(46): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): ApiController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): ApiController->runActionWithFilters()
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ApiController->run()
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/api/Customer/list
in C:\xampp\htdocs\testyii\protected\controllers\APIController.php (46)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 22:54:22 [error] [php] include(Customer.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\testyii\protected\controllers\APIController.php(46): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): ApiController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): ApiController->runActionWithFilters()
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ApiController->run()
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/api/Customer/list
in C:\xampp\htdocs\testyii\protected\controllers\APIController.php (46)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 22:54:22 [error] [php] include(Customer.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\testyii\protected\controllers\APIController.php(46): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): ApiController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): ApiController->runActionWithFilters()
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ApiController->run()
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/api/Customer/list
in C:\xampp\htdocs\testyii\protected\controllers\APIController.php (46)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 22:54:22 [error] [php] include(Customer.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\testyii\protected\controllers\APIController.php(46): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): ApiController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): ApiController->runActionWithFilters()
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ApiController->run()
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/api/Customer/list
in C:\xampp\htdocs\testyii\protected\controllers\APIController.php (46)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 22:54:23 [error] [php] include(Customer.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\testyii\protected\controllers\APIController.php(46): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): ApiController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): ApiController->runActionWithFilters()
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ApiController->run()
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/api/Customer/list
in C:\xampp\htdocs\testyii\protected\controllers\APIController.php (46)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 22:54:23 [error] [php] include(Customer.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\testyii\protected\controllers\APIController.php(46): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): ApiController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): ApiController->runActionWithFilters()
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ApiController->run()
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/api/Customer/list
in C:\xampp\htdocs\testyii\protected\controllers\APIController.php (46)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 22:54:23 [error] [php] include(Customer.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\testyii\protected\controllers\APIController.php(46): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): ApiController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): ApiController->runActionWithFilters()
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ApiController->run()
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/api/Customer/list
in C:\xampp\htdocs\testyii\protected\controllers\APIController.php (46)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 22:54:23 [error] [php] include(Customer.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\testyii\protected\controllers\APIController.php(46): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): ApiController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): ApiController->runActionWithFilters()
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ApiController->run()
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/api/Customer/list
in C:\xampp\htdocs\testyii\protected\controllers\APIController.php (46)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 22:54:23 [error] [php] include(Customer.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\testyii\protected\controllers\APIController.php(46): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): ApiController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): ApiController->runActionWithFilters()
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ApiController->run()
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/api/Customer/list
in C:\xampp\htdocs\testyii\protected\controllers\APIController.php (46)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 22:54:23 [error] [php] include(Customer.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\testyii\protected\controllers\APIController.php(46): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): ApiController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): ApiController->runActionWithFilters()
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ApiController->run()
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/api/Customer/list
in C:\xampp\htdocs\testyii\protected\controllers\APIController.php (46)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 22:54:24 [error] [php] include(Customer.php): failed to open stream: No such file or directory (C:\xampp\htdocs\yii\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\testyii\protected\controllers\APIController.php(46): spl_autoload_call()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): ApiController->actionList()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): ApiController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): ApiController->runActionWithFilters()
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ApiController->run()
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#8 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/api/Customer/list
in C:\xampp\htdocs\testyii\protected\controllers\APIController.php (46)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/17 22:55:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "journalImpactFactor" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('journalImpactFa...')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('journalImpactFa...')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('api/journalImpa...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/index.php/api/journalImpactFactor
---
2014/10/17 22:55:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "JournalImpactFactor" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('JournalImpactFa...')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('JournalImpactFa...')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('api/JournalImpa...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/index.php/api/JournalImpactFactor
---
2014/10/17 22:57:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "JournalImpactFactor" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('JournalImpactFa...')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('JournalImpactFa...')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('api/JournalImpa...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/index.php/api/JournalImpactFactor
---
2014/10/17 22:59:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "JournalImpactFactor" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('JournalImpactFa...')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('JournalImpactFa...')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('api/JournalImpa...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/index.php/api/JournalImpactFactor
---
2014/10/17 22:59:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "JournalImpactFactor" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('JournalImpactFa...')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('JournalImpactFa...')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('api/JournalImpa...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/index.php/api/JournalImpactFactor
---
2014/10/17 23:14:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api1/JournalScimago/list".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('api1/JournalSci...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/index.php/api1/JournalScimago/list
---
2014/10/17 23:14:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "api1/JournalScimago/list".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('api1/JournalSci...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/index.php/api1/JournalScimago/list
---
2014/10/17 23:14:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "ApiController1/JournalScimago/list".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('ApiController1/...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/index.php/ApiController1/JournalScimago/list
---
2014/10/18 00:00:04 [error] [php] Undefined variable: model (C:\xampp\htdocs\testyii\protected\controllers\APIController.php:93)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(286): ApiController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(265): ApiController->runActionWithFilters()
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ApiController->run()
#3 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/api/JournalScimago/2
in C:\xampp\htdocs\testyii\protected\controllers\APIController.php (93)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/18 00:00:11 [error] [php] Undefined variable: model (C:\xampp\htdocs\testyii\protected\controllers\APIController.php:93)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(286): ApiController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(265): ApiController->runActionWithFilters()
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ApiController->run()
#3 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/api/JournalScimago/3
in C:\xampp\htdocs\testyii\protected\controllers\APIController.php (93)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/18 00:00:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "JournalScimago" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('JournalScimago')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('JournalScimago')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('api/JournalScim...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/index.php/api/JournalScimago
---
2014/10/18 00:00:28 [error] [php] Undefined variable: model (C:\xampp\htdocs\testyii\protected\controllers\APIController.php:93)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(286): ApiController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(265): ApiController->runActionWithFilters()
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ApiController->run()
#3 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/api/JournalScimago/1
in C:\xampp\htdocs\testyii\protected\controllers\APIController.php (93)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/18 00:01:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "JournalScimago" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('JournalScimago')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('JournalScimago')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('api/JournalScim...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/index.php/api/JournalScimago/post
---
2014/10/18 00:01:38 [error] [php] Undefined variable: model (C:\xampp\htdocs\testyii\protected\controllers\APIController.php:93)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(286): ApiController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(265): ApiController->runActionWithFilters()
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ApiController->run()
#3 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/api/JournalScimago/3
in C:\xampp\htdocs\testyii\protected\controllers\APIController.php (93)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/18 00:02:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "JournalImpactFactor" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('JournalImpactFa...')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('JournalImpactFa...')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('api/JournalImpa...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/index.php/api/JournalImpactFactor/id
---
2014/10/18 00:15:53 [error] [php] Undefined variable: model (C:\xampp\htdocs\testyii\protected\controllers\APIController.php:93)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(286): ApiController->runAction()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(265): ApiController->runActionWithFilters()
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): ApiController->run()
#3 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\testyii\index.php(13): CWebApplication->run()
REQUEST_URI=/testyii/index.php/api/JournalScimago/3
in C:\xampp\htdocs\testyii\protected\controllers\APIController.php (93)
in C:\xampp\htdocs\testyii\index.php (13)
2014/10/26 20:15:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "list" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('list')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('list')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('JournalImpactFa...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/JournalImpactFactor/list
---
2014/10/26 20:18:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/JournalImpactFactor/list".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/JournalImpa...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/gii/JournalImpactFactor/list
---
2014/10/26 20:18:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/JournalImpactFactor".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/JournalImpa...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/gii/JournalImpactFactor
---
2014/10/26 20:19:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "profile".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('profile')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/profile
HTTP_REFERER=http://drivesoftcenter.net/tutorial/yii/%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B8%87%E0%B8%B2%E0%B8%99-Gii-%E0%B8%82%E0%B8%AD%E0%B8%87-Yii-Framework
---
2014/10/26 20:19:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "sale".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('sale')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/sale/
HTTP_REFERER=http://drivesoftcenter.net/tutorial/yii/%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B9%83%E0%B8%8A%E0%B9%89%E0%B8%87%E0%B8%B2%E0%B8%99-Gii-%E0%B8%82%E0%B8%AD%E0%B8%87-Yii-Framework
---
2014/10/26 20:20:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "member".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('member')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/member
HTTP_REFERER=http://drivesoftcenter.net/tutorial/yii/%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%94%E0%B8%B6%E0%B8%87%E0%B8%82%E0%B9%89%E0%B8%AD%E0%B8%A1%E0%B8%B9%E0%B8%A5%E0%B8%88%E0%B8%B2%E0%B8%81%E0%B8%90%E0%B8%B2%E0%B8%99%E0%B8%82%E0%B9%89%E0%B8%AD%E0%B8%A1%E0%B8%B9%E0%B8%A5
---
2014/10/26 20:22:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "list" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('list')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('list')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('JournalImpactFa...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/JournalImpactFactor/list
---
2014/10/26 20:22:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "view/JournalImpactFactor/list".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('view/JournalImp...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/view/JournalImpactFactor/list
---
2014/10/26 20:24:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "APIcontroller".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('APIcontroller')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/APIcontroller
---
2014/10/26 21:06:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "APIController".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('APIController')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/APIController
---
2014/10/26 21:06:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "JournalImpactFactorController/list".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('JournalImpactFa...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/JournalImpactFactorController/list
---
2014/10/26 21:06:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "list" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('list')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('list')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('JournalImpactFa...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/JournalImpactFactor/list
---
2014/10/26 21:07:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "JrnalImpactFactor".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('JrnalImpactFact...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/JrnalImpactFactor
---
2014/10/26 22:44:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/JournalImpactFactor".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/JournalImpa...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/index.php/gii/JournalImpactFactor
---
2014/10/26 22:44:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/JournalImpactFactor/list".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/JournalImpa...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/index.php/gii/JournalImpactFactor/list
---
2014/10/26 22:44:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/JournalImpactFactor/list".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/JournalImpa...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/gii/JournalImpactFactor/list
---
2014/10/26 22:44:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/gii/index
---
2014/10/26 22:44:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/journalScimago".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/journalScim...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/gii/journalScimago
---
2014/10/26 22:44:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "list" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('list')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('list')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('journalScimago/...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/journalScimago/list
---
2014/10/26 22:45:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/journalScimago/list".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/journalScim...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/gii/journalScimago/list
---
2014/10/26 22:48:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/index?r=gii
---
2014/10/26 22:49:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/journalScimago".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/journalScim...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/index.php/gii/journalScimago
---
2014/10/26 22:49:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/journalScimago/list".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/journalScim...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/index.php/gii/journalScimago/list
---
2014/10/26 22:51:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/main.php".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/main.php')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/index.php/gii/main.php
---
2014/10/26 22:51:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/main.php".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/main.php')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/gii/main.php
---
2014/10/26 22:51:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gi".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gi')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/gi
---
2014/10/26 22:51:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/main.php".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/main.php')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/gii/main.php
---
2014/10/26 22:52:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/journalScimago".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/journalScim...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/gii/journalScimago
---
2014/10/26 22:52:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/views/journalScimago".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/views/journ...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/gii/views/journalScimago
---
2014/10/26 22:56:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "JournalImpactFactorController".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('JournalImpactFa...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/JournalImpactFactorController
---
2014/10/26 22:56:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "JournalImpactFactorController/list".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('JournalImpactFa...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/JournalImpactFactorController/list
---
2014/10/26 22:56:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "JournalImpactFactorController".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('JournalImpactFa...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/JournalImpactFactorController
---
2014/10/26 23:10:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "views".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('views')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/views
---
2014/10/26 23:10:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "view".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('view')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/view
---
2014/10/26 23:10:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "view.php".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('view.php')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/view.php
---
2014/10/26 23:10:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "list" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('list')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('list')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('journalScimago/...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/journalScimago/list
---
2014/10/26 23:10:33 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('journalScimago/...')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/testyii/journalScimago/view
---
2014/10/26 23:10:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "view.php" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('view.php')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view.php')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('journalScimago/...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/journalScimago/view.php
---
2014/10/26 23:10:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "_view.php" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('_view.php')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('_view.php')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('journalScimago/...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/journalScimago/_view.php
---
2014/10/26 23:11:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "JournalImpactFactor.php".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('JournalImpactFa...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/JournalImpactFactor.php
---
2014/10/26 23:14:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "app/protected/views".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('app/protected/v...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/app/protected/views
---
2014/10/26 23:19:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "journalScimago" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('journalScimago')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('journalScimago')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('api/journalScim...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/index.php/api/journalScimago
---
2014/10/26 23:23:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "journalScimago" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('journalScimago')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('journalScimago')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('api/journalScim...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/index.php/api/journalScimago
---
2014/10/26 23:23:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "list" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('list')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('list')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('journalScimago/...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/index.php/journalScimago/list
---
2014/10/27 11:05:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "apiJournalImpactFactor".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('apiJournalImpac...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testyii/index.php/apiJournalImpactFactor
---
2014/10/27 11:05:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "JournalImpactFactor" ตามคำสั่งได้' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('JournalImpactFa...')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('JournalImpactFa...')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('api/JournalImpa...')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testyii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testyii/index.php/api/JournalImpactFactor
---
